### ISSUE TITLE
Hello Sir, I'm a total beginner trying this code out and I'm getting an error can you help me out?

### ISSUE THREAD

**Issue by Sanjeeth8733** [ljvmiranda921/pyswarms#256]
CODE
============================

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from tensorflow.contrib import learn
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn import datasets, linear_model
from sklearn import model_selection
from sklearn import preprocessing

import tensorflow as tf
import pyswarms as ps
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math
import calendar
import time





from IPython import get_ipython
ipython = get_ipython()

if '__IPYTHON__' in globals():
    ipython.magic('load_ext autoreload')
    ipython.magic('autoreload 2')
    
# Load the iris dataset




# Load the dataset
region = "iris"
filename = region + ".csv"

x = np.array(pd.read_csv(filename, usecols=[1], header=None))
y = np.array(pd.read_csv(filename, usecols=[3], header=None))

normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.2222222222222222, shuffle=False, stratify=None)
print(Y_train)
import numpy as np
Y_train_new = Y_train.ravel()
le = preprocessing.LabelEncoder()
le.fit(Y_train_new)
le.classes_
Y_train_transformed = le.transform(Y_train_new)
le.inverse_transform(le.transform(Y_train_new))
print(Y_train_new)
print(Y_train_transformed)


# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = params[0:80].reshape((n_inputs,n_hidden))
    b1 = params[80:100].reshape((n_hidden,))
    W2 = params[100:120].reshape((n_hidden,n_classes))
    b2 = params[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = 84 # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    return loss

def f(X_train):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (4 * 20) + (20 * 1) + 20 + 1
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)

# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = pos[0:80].reshape((n_inputs,n_hidden))
    b1 = pos[80:100].reshape((n_hidden,))
    W2 = pos[100:120].reshape((n_hidden,n_classes))
    b2 = pos[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    print(y_pred)
    return y_pred

(predict(X_train, pos) == Y_train).mean()
================================
Error:
File "/anaconda3/lib/python3.6/site-packages/pyswarms-0.3.1-py3.6.egg/pyswarms/single/global_best.py", line 167, in optimize
    self.swarm.position, *kwargs

TypeError: f() takes 1 positional argument but 3 were given
```
_Originally posted by @Sanjeeth8733 in https://github.com/ljvmiranda921/pyswarms/issues/41#issuecomment-433631657_

**Comment by ljvmiranda921** [comment]
Hi @Sanjeeth8733 , 

It seems that the problem is coming from this line of code:

```python
def f(X_train):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)
```

Would you mind checking what `X_train` looks like? 
Also, I'm curious if you are using the `master` or `development` branch. If you're using the latter, then maybe you can use the `@cost` decorator (not yet merged to master).

cc: @whzup

**Comment by Sanjeeth8733** [comment]
> Hi @Sanjeeth8733 ,
> 
> It seems that the problem is coming from this line of code:
> 
> ```python
> def f(X_train):
>     n_particles = 100
>     j = [forward_prop(X_train[i]) for i in range(n_particles)]
>     return np.array(j)
> ```
> 
> Would you mind checking what `X_train` looks like?
> Also, I'm curious if you are using the `master` or `development` branch. If you're using the latter, then maybe you can use the `@cost` decorator (not yet merged to master).
> 
> cc: @whzup
Hello @ljvmiranda921 
Thank you for your reply sir,
the result for X_train was 
==========================
2018-10-30 20:25:33,536 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best:   0%|          |0/1000[[-0.90068117]
 [-1.14301691]
 [-1.38535265]
 [-1.50652052]
 [-1.02184904]
 [-0.53717756]
 [-1.50652052]
 [-1.02184904]
 [-1.74885626]
 [-1.14301691]
 [-0.53717756]
 [-1.26418478]
 [-1.26418478]
 [-1.87002413]
 [-0.05250608]
 [-0.17367395]
 [-0.53717756]
 [-0.90068117]
 [-0.17367395]
 [-0.90068117]
 [-0.53717756]
 [-0.90068117]
 [-1.50652052]
 [-0.90068117]
 [-1.26418478]
 [-1.02184904]
 [-1.02184904]
 [-0.7795133 ]
 [-0.7795133 ]
 [-1.38535265]
 [-1.26418478]
 [-0.53717756]
 [-0.7795133 ]
 [-0.41600969]
 [-1.14301691]
 [-1.02184904]
 [-0.41600969]
 [-1.14301691]
 [-1.74885626]
 [-0.90068117]
 [-1.02184904]
 [-1.62768839]
 [-1.74885626]
 [-1.02184904]
 [-0.90068117]
 [-1.26418478]
 [-0.90068117]
 [-1.50652052]
 [-0.65834543]
 [-1.02184904]
 [ 1.40150837]
 [ 0.67450115]
 [ 1.2803405 ]
 [-0.41600969]
 [ 0.79566902]
 [-0.17367395]
 [ 0.55333328]
 [-1.14301691]
 [ 0.91683689]
 [-0.7795133 ]
 [-1.02184904]
 [ 0.06866179]
 [ 0.18982966]
 [ 0.31099753]
 [-0.29484182]
 [ 1.03800476]
 [-0.29484182]
 [-0.05250608]
 [ 0.4321654 ]
 [-0.29484182]
 [ 0.06866179]
 [ 0.31099753]
 [ 0.55333328]
 [ 0.31099753]
 [ 0.67450115]
 [ 0.91683689]
 [ 1.15917263]
 [ 1.03800476]
 [ 0.18982966]
 [-0.17367395]
 [-0.41600969]
 [-0.41600969]
 [-0.05250608]
 [ 0.18982966]
 [-0.53717756]
 [ 0.18982966]
 [ 1.03800476]
 [ 0.55333328]
 [-0.29484182]
 [-0.41600969]
 [-0.41600969]
 [ 0.31099753]
 [-0.05250608]
 [-1.02184904]
 [-0.29484182]
 [-0.17367395]
 [-0.17367395]
 [ 0.4321654 ]
 [-0.90068117]
 [-0.17367395]
 [ 0.55333328]
 [-0.05250608]
 [ 1.52267624]
 [ 0.55333328]
 [ 0.79566902]
 [ 2.12851559]
 [-1.14301691]
 [ 1.76501198]
 [ 1.03800476]
 [ 1.64384411]
 [ 0.79566902]
 [ 0.67450115]
 [ 1.15917263]
 [-0.17367395]
 [-0.05250608]
 [ 0.67450115]]
Traceback (most recent call last):

  File "<ipython-input-1-00d46cf4e803>", line 1, in <module>
    runfile('/Users/sanjeethrao/Downloads/ml/untitled9.py', wdir='/Users/sanjeethrao/Downloads/ml')

  File "/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/sanjeethrao/Downloads/ml/untitled9.py", line 107, in <module>
    cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)

  File "/anaconda3/lib/python3.6/site-packages/pyswarms-0.3.1-py3.6.egg/pyswarms/single/global_best.py", line 167, in optimize
    self.swarm.position, *kwargs

TypeError: f() takes 1 positional argument but 3 were given
==========================================================================
I used the standard code which takes iris dataset directly which seams to be working, but i need this code to work in any dataset i take in as input.
==========================================================================
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function



import pyswarms as ps
import numpy as np


# Python version
import sys
print('Python: {}'.format(sys.version))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))



from IPython import get_ipython
ipython = get_ipython()

if '__IPYTHON__' in globals():
    ipython.magic('load_ext autoreload')
    ipython.magic('autoreload 2')
from sklearn.datasets import load_iris    


# Load the iris dataset

 # Load the iris dataset
data = load_iris()
X = data.data
y = data.target



print(X)
print(y)




def forward_prop(params):

# Neural network architecture
    n_inputs = 4
    n_hidden = 20
    n_classes = 3
# Roll-back the weights and biases
    W1 = params[0:80].reshape((n_inputs,n_hidden))
    b1 = params[80:100].reshape((n_hidden,))
    W2 = params[100:160].reshape((n_hidden,n_classes))
    b2 = params[160:163].reshape((n_classes,))
    
# Perform forward propagation
    z1 = X.dot(W1) + b1 # Pre-activation in Layer 1 
    a1 = np.tanh(z1) # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2 
    logits = z2 # Logits for Layer 2
# Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
# Compute for the negative log likelihood
    N = 150 # Number of samples
    corect_logprobs = -np.log(probs[range(N),y]) 
    loss = np.sum(corect_logprobs) / N
    return loss
print('--------------------------------------------------')
def f(x,y,z):

    n_particles = x.shape[0]

    j = [forward_prop(x[i]) for i in range(n_particles)]
    return np.array(j)
print('-------------------------------------------------')


# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}
# Call instance of PSO
dimensions = (4 * 20) + (20 * 3) + 20 + 3
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)
# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)
def predict(X, pos):
    # Neural network architecture
    n_inputs = 4
    n_hidden = 20
    n_classes = 3
    # Roll-back the weights and biases
    W1 = pos[0:80].reshape((n_inputs,n_hidden))
    b1 = pos[80:100].reshape((n_hidden,))
    W2 = pos[100:160].reshape((n_hidden,n_classes))
    b2 = pos[160:163].reshape((n_classes,))
# Perform forward propagation
    z1 = X.dot(W1) + b1 # Pre-activation in Layer 1 
    a1 = np.tanh(z1) # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2 # Logits for Layer 2
    y_pred = np.argmax(logits, axis=1) 
    return y_pred
A=(predict(X, pos) == y).mean()
print('______________#ACCURACY is in %#_________________')
print('-------------------------------------------------')
print(A*100)
print('-------------------------------------------------')
=================output======================
2018-10-30 20:37:37,310 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best:   0%|          |0/1000[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
--------------------------------------------------
-------------------------------------------------
pyswarms.single.global_best: 100%|██████████|1000/1000, best_cost=0.0346
2018-10-30 20:38:21,983 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 0.0345689346011975, best pos: [ 3.16505472e-01 -4.82484245e-01 -2.31268460e+00  3.74765599e-01
 -2.81491002e+00 -7.05082322e-01  1.00571512e-01  4.32123342e-01
  4.99243795e-02  1.28711176e-01 -1.37655260e-01 -2.91427891e-01
  2.47779853e+00 -4.91863072e-01 -1.48507813e-03  2.10406996e-01
 -2.48244471e-01  1.15348984e+00  1.14364614e-01 -2.33365986e-01
 -8.79097977e-01 -5.75145158e-02  4.76921963e-01 -7.64203393e-01
 -4.66265799e-01  1.77209257e-01  6.14939810e-01 -2.70083601e+00
  3.17714660e-01 -8.00474263e-01  1.29212346e-01 -2.27070181e+00
  4.48442843e-01 -2.92094419e-01  4.84925510e-01  7.34442964e-01
  7.58602468e-01 -8.22965694e-01  1.13582325e+00 -4.95552276e-01
  7.37059083e-01  2.82733101e-01  2.83930824e+00 -2.50658003e-01
 -2.94793093e-01  8.25843936e-01 -7.07000516e-01 -9.10578409e-03
 -1.55886265e+00  4.48521839e-01 -7.25571759e-01  9.62992366e-01
  1.91809000e+00  3.82734865e-01  1.39149611e+00 -4.92101342e-01
  1.29029277e+00 -1.07426735e+00 -1.39125127e+00  3.13650969e-01
 -2.78324459e-01  1.21701322e+00 -1.84454256e+00  1.11438297e+00
 -1.89466166e+00  7.10182138e-01 -2.44476073e-01  4.62499637e-02
 -7.59913102e-01  1.04351796e-01  5.70957879e-01 -8.49455395e-01
  1.93853249e-01 -2.63679686e+00  5.05794537e-01 -2.35954105e+00
  1.21088059e+00 -6.66984223e-01 -1.69299389e+00  6.93951600e-01
 -1.78241404e-01  1.53146341e-03 -3.54648605e-01 -1.95457553e+00
 -9.28014220e-01  2.42018735e-01 -1.81131393e-01 -1.14470780e+00
 -5.78022646e-01 -3.73122103e-01 -9.76040152e-01 -1.62670883e+00
 -2.44070851e-02 -4.53101415e-01 -2.44953391e+00  3.41276216e-01
 -5.54362021e-01  1.41063654e-01  4.40823581e+00  7.26671395e-02
 -4.53666959e-01  2.51276110e+00  4.13452050e-01 -1.03444071e+00
  5.96635853e-01 -4.26109614e-01 -3.39989684e-01 -9.51984846e-01
 -8.79906693e-01 -1.70654977e+00 -1.27613650e+01  1.16553788e+01
 -1.74044298e-01 -3.82797316e-01  9.61146083e-02 -8.16638566e-01
  5.08272166e-01  8.29951653e-01  3.68013174e+00 -1.28809026e+00
 -5.42546960e-01 -5.09598504e-01 -7.00600359e-01  7.58566093e-01
 -3.37789815e-01  2.04646102e-01  4.98911923e+00 -2.04721665e-01
  2.78810123e-02 -3.21386292e-01 -7.25155783e+00 -4.16220512e+00
  6.42817641e-01  8.34137736e-02  3.17568011e-02  2.06407950e+00
  4.27784324e-01  5.38241551e-01 -8.38360826e-03 -1.53263243e+00
 -1.91195456e-01 -9.11813611e-02  7.17258650e-01 -3.79113688e-02
 -3.05707866e-01 -1.79728956e-01 -8.80471262e-01 -8.01403660e-01
  2.86995870e-01 -4.93514061e-01 -2.40786856e-01  3.90407211e-01
 -9.18633561e-01 -2.73537140e+01 -2.26903889e-01 -6.39679048e-01
 -2.49401911e+01 -8.72202084e+00 -3.49368607e-02 -4.51846177e-01
 -1.97194318e+00  1.07679697e+00 -5.45154479e+00]
______________#ACCURACY is in %#_________________
-------------------------------------------------
98.66666666666667
-------------------------------------------------

**Comment by whzup** [comment]
@ljvmiranda921 that looks weird to me. @Sanjeeth8733 Maybe try to change the `print_step` and `iters` keywords around. From this:
```python
# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=1000, verbose=3)
```
To that:
```python
# Perform optimization
cost, pos = optimizer.optimize(f, iters=1000, print_step=100, verbose=3)
```
I don't think this will change a lot but frankly, it's the only thing I can see an error in 😕 I feel like Anaconda might misinterpret the keywords for kwargs and feed it into the objective function instead of using them as function "keys".

**Comment by Sanjeeth8733** [comment]
> cost, pos = optimizer.optimize(f, iters=1000, print_step=100, verbose=3)

Hello@whzup and @ljvmiranda921  did the changes mentioned by you, code :
___________________________________________________________________________________
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from tensorflow.contrib import learn
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn import datasets, linear_model
from sklearn import model_selection
from sklearn import preprocessing

import tensorflow as tf
import pyswarms as ps
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math
import calendar
import time





from IPython import get_ipython
ipython = get_ipython()

if '__IPYTHON__' in globals():
    ipython.magic('load_ext autoreload')
    ipython.magic('autoreload 2')
    
# Load the iris dataset




# Load the dataset
region = "iriscopy"
filename = region + ".csv"

x = np.array(pd.read_csv(filename, usecols=[1], header=None))
y = np.array(pd.read_csv(filename, usecols=[3], header=None))

normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.2222222222222222, shuffle=False, stratify=None)
print(Y_train)
import numpy as np
Y_train_new = Y_train.ravel()
le = preprocessing.LabelEncoder()
le.fit(Y_train_new)
le.classes_
Y_train_transformed = le.transform(Y_train_new)
le.inverse_transform(le.transform(Y_train_new))
print(Y_train_new)
print(Y_train_transformed)


# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = params[0:80].reshape((n_inputs,n_hidden))
    b1 = params[80:100].reshape((n_hidden,))
    W2 = params[100:120].reshape((n_hidden,n_classes))
    b2 = params[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = 84 # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    return loss

def f(X_train,y,z):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (4 * 20) + (20 * 1) + 20 + 1
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)

# Perform optimization

cost, pos = optimizer.optimize(f, iters=1000, print_step=100, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 1

    # Roll-back the weights and biases
    W1 = pos[0:80].reshape((n_inputs,n_hidden))
    b1 = pos[80:100].reshape((n_hidden,))
    W2 = pos[100:120].reshape((n_hidden,n_classes))
    b2 = pos[120:121].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    print(y_pred)
    return y_pred

(predict(X_train, pos) == Y_train).mean()
_________________________________________________________
error obtained is:
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
2018-10-31 01:45:01,987 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best:   0%|          |0/1000Traceback (most recent call last):

  File "<ipython-input-1-3fd04dc575f6>", line 1, in <module>
    runfile('/Users/sanjeethrao/Downloads/ml/untitled10.py', wdir='/Users/sanjeethrao/Downloads/ml')

  File "/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/sanjeethrao/Downloads/ml/untitled10.py", line 109, in <module>
    cost, pos = optimizer.optimize(f, iters=1000, print_step=100, verbose=3)

  File "/anaconda3/lib/python3.6/site-packages/pyswarms-0.3.1-py3.6.egg/pyswarms/single/global_best.py", line 167, in optimize
    self.swarm.position, *kwargs

  File "/Users/sanjeethrao/Downloads/ml/untitled10.py", line 97, in f
    j = [forward_prop(X_train[i]) for i in range(n_particles)]

  File "/Users/sanjeethrao/Downloads/ml/untitled10.py", line 97, in <listcomp>
    j = [forward_prop(X_train[i]) for i in range(n_particles)]

  File "/Users/sanjeethrao/Downloads/ml/untitled10.py", line 74, in forward_prop
    W1 = params[0:80].reshape((n_inputs,n_hidden))

ValueError: cannot reshape array of size 80 into shape (1,20)

cc: @ljvmiranda921

**Comment by Sanjeeth8733** [comment]
Thank you for your help sir, the code is working.

# Import modules
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from sklearn import model_selection
from sklearn import preprocessing


import pyswarms as ps
import numpy as np
import pandas as pd


import matplotlib.pyplot as plt



from matplotlib import animation
from matplotlib import rc
from IPython.display import HTML
# Import PySwarms


from pyswarms.utils.plotters import (plot_cost_history, plot_contour, plot_surface)

# Import PySwarms
# Import modules


dataset = pd.read_csv("testing.csv")
from IPython import get_ipython
ipython = get_ipython()

if '__IPYTHON__' in globals():
    ipython.magic('load_ext autoreload')
    ipython.magic('autoreload 2')

# Load the dataset

region = "testingX"
filename = region + ".csv"




x = np.array(pd.read_csv(filename, usecols=[0,1,2,3,4,5,6,7,8,9], header=None))
y = np.array(pd.read_csv(filename, usecols=[10], header=None))







normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.32, shuffle=False, stratify=None)


print("------------------")
print(Y_train.shape[0])
print("------------------")

Y_train_new = Y_train.ravel()


le = preprocessing.LabelEncoder()
le.fit(Y_train_new)
le.classes_
Y_train_transformed = le.transform(Y_train_new)
le.inverse_transform(le.transform(Y_train_new))
'''
print(Y_train_transformed)
print("------------------")
print(Y_train_new)
print("------------------")
print(Y_train)
print("------------------")
print(X_train.shape[1])
'''

# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 2

    # Roll-back the weights and biases
    W1 = params[0:200].reshape((n_inputs,n_hidden))
    b1 = params[200:220].reshape((n_hidden,))
    W2 = params[220:260].reshape((n_hidden,n_classes))
    b2 = params[260:262].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = Y_train.shape[0] # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    
    return loss


def f(X_train, X_test, Y_train):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (X_train.shape[1] * 20) + (20 * 2) + 20 + 2
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)
print(dimensions)
print(optimizer)
# Perform optimization
cost, pos = optimizer.optimize(f, print_step=100, iters=10, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 2

    # Roll-back the weights and biases
    W1 = pos[0:200].reshape((n_inputs,n_hidden))
    b1 = pos[200:220].reshape((n_hidden,))
    W2 = pos[220:260].reshape((n_hidden,n_classes))
    b2 = pos[260:262].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    
    return y_pred

A=(predict(X_train, pos) == Y_train).mean()
print("_____________________Accurecy____________________")
print('|\t\t',100*A,'%\t\t|')
print("_________________________________________________")


plot_cost_history(cost_history=optimizer.cost_history)
plt.show()

**Comment by whzup** [comment]
So is this solved now? 😄 I wonder what the actual problem was @Sanjeeth8733 ?🤔

**Comment by Sanjeeth8733** [comment]
@whzup 
the error still persists 
after I randomly added some variables into f() as you can see below.

# Import modules
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from sklearn import model_selection
from sklearn import preprocessing


import pyswarms as ps
import numpy as np
import pandas as pd


import matplotlib.pyplot as plt


from pyswarms.utils.plotters import plot_cost_history
from pyswarms.utils.plotters.formatters import Designer
from matplotlib import animation
from matplotlib import rc
from IPython.display import HTML
# Import PySwarms


from pyswarms.utils.plotters import (plot_cost_history, plot_contour, plot_surface)

# Import PySwarms
# Import modules



from IPython import get_ipython
ipython = get_ipython()

if '__IPYTHON__' in globals():
    ipython.magic('load_ext autoreload')
    ipython.magic('autoreload 2')

# Load the dataset

region = "testing"
filename = region + ".csv"

x = np.array(pd.read_csv(filename, usecols=[0,1,2,3,4,5,6,7,8,9]))
y = np.array(pd.read_csv(filename, usecols=[10]))

"""
x = np.array(pd.read_csv(filename, usecols=[0,1,2,3,4,5,6,7,8,9], header=None))
y = np.array(pd.read_csv(filename, usecols=[10], header=None))
"""
print("------------------")



normalized_X = preprocessing.scale(x)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(
normalized_X, y, test_size=0.32, shuffle=False, stratify=None)

'''
print("------------------")
print(Y_train.shape[0])
print("------------------")
'''
Y_train_new = Y_train.ravel()


le = preprocessing.LabelEncoder()
le.fit(Y_train_new)
le.classes_
Y_train_transformed = le.transform(Y_train_new)
le.inverse_transform(le.transform(Y_train_new))
'''
print(Y_train_transformed)
print("------------------")
print(Y_train_new)
print("------------------")
print(Y_train)
print("------------------")
print(X_train.shape[1])
print("------------------")
    print(W1)
    print("------------------")
'''

# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 2

    # Roll-back the weights and biases
    W1 = params[0:200].reshape((n_inputs,n_hidden))
    b1 = params[200:220].reshape((n_hidden,))
    W2 = params[220:260].reshape((n_hidden,n_classes))
    b2 = params[260:262].reshape((n_classes,))
    
    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    # Compute for the negative log likelihood
    N = Y_train.shape[0] # Number of samples
    correct_logprobs = -np.log(probs[range(N), Y_train])
    loss = np.sum(correct_logprobs) / N
    
    return loss


def f(X_train, X_test,alpha=0.88):
    n_particles = 100
    j = [forward_prop(X_train[i]) for i in range(n_particles)]
    return np.array(j)

# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.91}

# Call instance of PSO
dimensions = (X_train.shape[1] * 20) + (20 * 2) + 20 + 2
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)
print(dimensions)
print(optimizer)
# Perform optimization
cost, pos = optimizer.optimize(f, print_step=10, iters=2, verbose=3)

def predict(X_train, pos):
    # Neural network architecture
    n_inputs = X_train.shape[1]
    n_hidden = 20
    n_classes = 2

    # Roll-back the weights and biases
    W1 = pos[0:200].reshape((n_inputs,n_hidden))
    b1 = pos[200:220].reshape((n_hidden,))
    W2 = pos[220:260].reshape((n_hidden,n_classes))
    b2 = pos[260:262].reshape((n_classes,))

    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    
    return y_pred

A=(predict(X_train, pos) == Y_train).mean()
print('=================================================')
print('=================================================')
print('=================================================')
print("_____________________Accurecy____________________")
print('|\t\t',100*A,'%\t\t|')
print("_________________________________________________")
print('=================================================')
print('=================================================')
"""


Plotting the cost history
To plot the cost history, we simply obtain the cost_history from the optimizer class and pass it to the cost_history function.
Furthermore, this method also accepts a keyword argument **kwargs similar to matplotlib. This enables us to further customize various artists and elements in the plot.
In addition, we can obtain the following histories from the same class:
• mean_neighbor_history: average local best history of all neighbors throughout optimization 
• mean_pbest_history: average personal best of the particles throughout optimization
"""

plot_cost_history(cost_history=optimizer.cost_history)
plt.show()
